### ISSUE TITLE
What exactly is needed for the baby alphabet?

### ISSUE THREAD

**Issue by PeterAlfonsLoch** [alc6379/ardubaby-games#1]
could you elaborate based on your reddit post? maybe even a drawing or something? I would like trying to help you.

**Comment by alc6379** [comment]
Sure! 

So, it's really simple right now. It plays the "ABC" song. For each letter it displays, it should play the corresponding note in the ABC song. Of course, it gets a bit wonky when you want to play 3 notes for W, because then you can't just map 1:1 to the arrays I have set up currently. 

What winds up happening is that X and Y's tones wind up being the 2nd and 3rd syllables for W, and then Z's note becomes the note for X. 

I haven't had time to address this, really. I've been kind of swamped with work and other projects.

**Comment by PeterAlfonsLoch** [comment]
so basically the user is cycling thoug the alphabet and the letter that appears is associated by the note that it has in the song?

My arduboy should arrive tommorow I have used the emulator tho, i'll try to help^^

**Comment by alc6379** [comment]
Sure! If you can think of a better way to do it than I already am, that would be awesome. But yes, that's exactly what's happening. Each letter corresponds with the note in the song. As the user cycles through, it should play the note(s) associated with the letter. 

I'm super inexperienced in C++. But if this were a language like Python or similar, I could use a Dictionary or a HashMap to iterate through, using the letter as the key, and then making an array for which notes to play. There might be a way to do that in C++, I'm not sure.

**Comment by PeterAlfonsLoch** [comment]
I had to listen to the song, as i didn't know the english version (we pronounce W differently so it's one note) but I see the issue. First i will try making it work, then i will try to cleanup the code ;)

**Comment by alc6379** [comment]
Oh, right-- in English it's pronounced like "double U". I forget that in some languages like German and the like, it's one syllable. What's funny is that usually (like in German), Y is pronounced "ypsilon", so the number of notes in the Alphabet song still work out the same. Localization opportunity, perhaps? 😃

**Comment by PeterAlfonsLoch** [comment]
in my languge we sometimes even say igrek istead of ypsilon  my native language is luxembourgish wich has the same germanic routes as german, dutch or danish (and many others)
